[workspace]

members = [
    "blessed-contracts/mint-token",
    "blessed-contracts/test-mint-token",
    "comm",
    "common",
    "engine",
    "metrics-scraper",
    "shared",
    "storage",
    "test-contracts/transfer-to-account-01",
    "test-contracts/transfer-to-account-02",
    "test-contracts/local-state",
    "wasm-prep",
]
