/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExecutionEngine */

#ifndef _Included_ExecutionEngine
#define _Included_ExecutionEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExecutionEngine
 * Method:    init
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ExecutionEngine_init
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     ExecutionEngine
 * Method:    destroy
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ExecutionEngine_destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ExecutionEngine
 * Method:    exec
 * Signature: (Ljava/lang/Object;[BJ[LExecutionEngine/Deploy;J)V
 */
JNIEXPORT void JNICALL Java_ExecutionEngine_exec
  (JNIEnv *, jclass, jobject, jbyteArray, jlong, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
