[package]
name = "standard-payment"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-standard-payment/std", "contract/std", "types/std"]
lib = []

[dependencies]
casperlabs-standard-payment = { path = "../../../standard-payment" }
contract = { path = "../../../contract", package = "casperlabs-contract" }
proof-of-stake = { path = "../../../proof-of-stake", package = "casperlabs-proof-of-stake" }
types = { path = "../../../types", package = "casperlabs-types" }
