[package]
name = "known-urefs"
version = "0.1.0"
authors = ["Michał Papierski <michal@casperlabs.io>"]
edition = "2018"

[lib]
name = "known_urefs"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std" ]

[dependencies]
cl_std = { path = "../../common", package = "casperlabs-contract-ffi" }
